import re, json, traceback

content = open('src/data/rules.ts', encoding='utf-8').read()

reps = {
    '- 只在需要交互时使用 Client Component': '- Use Client Components only when interactivity is required',
    '- 使用 Server Actions 处理表单': '- Use Server Actions for form mutations',
    '- 每个页面必须有 metadata': '- Every page must export metadata',
    '- 使用 generateMetadata 动态生成': '- Use generateMetadata for dynamic page metadata',
    '- 图片必须包含 alt 属性': '- Images must include alt attributes',
    '- 链接使用 next/link': '- Use next/link for client-side navigation',
    '- 动态导入使用 next/dynamic': '- Use next/dynamic for code-split imports',
    '- 行最大长度 88（Black 默认）': '- Max line length: 88 characters (Black default)',
    '- 使用蛇形命名法': '- Use snake_case for functions and variables',
    '## 类型提示': '## Type Hints',
    '- 所有函数参数和返回值必须标注类型': '- All function params and return types must be annotated',
    '- 使用 typing 模块': '- Use the typing module for type utilities',
    '- 复杂类型使用 TypeAlias': '- Use TypeAlias for complex types',
    '## 项目管理': '## Project Management',
    '- 使用 pyproject.toml': '- Use pyproject.toml for project configuration',
    '- 依赖分组管理（dev/prod）': '- Split dependencies into dev and production groups',
    '- 测试使用 pytest': '- Use pytest for testing',
    '- 公共函数必须写 docstring': '- All public functions must have docstrings',
    '- 使用 Google 风格的 docstring': '- Use Google-style docstrings',
    '- README 包含安装和使用说明': '- README must include install and usage instructions',
    '## 分支策略': '## Branching Strategy',
    '- main：生产分支，只接受 merge': '- main: production branch, accept merges only',
    '- dev：开发分支': '- dev: development integration branch',
    '- feature/*：功能分支': '- feature/*: feature branches',
    '- fix/*：修复分支': '- fix/*: fix branches',
    '## 提交规范': '## Commit Conventions',
    '- 使用 Conventional Commits': '- Use Conventional Commits format',
    '- 格式：type(scope): description': '- Format: type(scope): description',
    '## 提交前检查': '## Pre-Commit Checks',
    '- 运行 lint': '- Run the linter',
    '- 运行测试': '- Run full test suite',
    '- 检查未使用的导入': '- Check for unused imports',
    '- 检查控制台输出': '- Check for leftover console.log statements',
    '## PR 规范': '## Pull Request Standards',
    '- PR 标题使用简洁描述': '- PR title should clearly summarize the change',
    '- PR 描述包含改动原因': '- PR description must explain why the change is needed',
    '- 关联 Issue 编号': '- Link related issue numbers',
    '- 优先使用 interface 而不是 type': '- Prefer interface over type for object shapes',
    '- 联合类型使用 type': '- Use type aliases for union types',
    '- 避免 any，使用 unknown': '- Avoid any -- use unknown when type is uncertain',
    '## 泛型': '## Generics',
    '- 泛型参数使用 T 或完整单词': '- Generic parameters: T for single types, full words for multiple',
    '- 约束使用 extends': '- Use extends for generic constraints',
    '- 工具类型优先于手写': '- Prefer built-in utility types over hand-written ones',
    '- 使用 const 断言': '- Use const assertions for literal type narrowing',
    '- 使用 satisfies 操作符': '- Use the satisfies operator for type-safe object literals',
    '- 枚举使用 const enum': '- Prefer const enum for performance',
    '## 核心原则': '## Core Principles',
    '- Claude Code 是编程助手，不是替代品': '- Claude Code is an assistant, not a replacement for engineering decisions',
    '- 始终审查 AI 生成的代码': '- Always review AI-generated code before merging',
    '- 保持代码库的一致性': '- Maintain consistency in coding patterns across the codebase',
    '## Prompt 技巧': '## Prompt Tips',
    '- 明确指定技术栈和版本': '- Explicitly specify the tech stack and version',
    '- 提供上下文文件路径': '- Provide relevant file paths as context',
    '- 使用分步指令': '- Use step-by-step instructions for complex tasks',
    '- 不要将 API Key 写入代码': '- Never embed API keys or secrets in source code',
    '- 审查所有文件修改': '- Review every file modification before committing',
    '- 敏感操作手动确认': '- Require manual confirmation for destructive operations',
    '# Claude Code 通用规则': '# Claude Code General Standards',
    '# Claude Code React 开发 Prompt': '# Claude Code React Prompts',
    '## 创建组件 Prompt': '## Component Creation Prompt',
    '## 修复 Bug Prompt': '## Bug Fix Prompt',
    '## 重构 Prompt': '## Refactoring Prompt',
    '# Claude Code Python 开发 Prompt': '# Claude Code Python Prompts',
    '# Claude Code 工作流规则': '# Claude Code Workflow Standards',
    '## 日常开发流程': '## Daily Development Workflow',
    '1. 启动任务前阅读相关文件': '1. Read relevant files before starting a task',
    '2. 用自然语言描述需求': '2. Describe the requirement in natural language',
    '3. 审查 AI 生成的代码': '3. Review AI-generated code thoroughly',
    '4. 本地测试验证': '4. Test and verify locally',
    '5. 提交并记录': '5. Commit with descriptive messages',
    '## 代码审查流程': '## Code Review Workflow',
    '- 使用 Claude Code 进行预审查': '- Use Claude Code for an initial review pass',
    '- 检查边界情况': '- Verify edge cases and error handling paths',
    '- 性能影响评估': '- Assess performance impact of the changes',
    '## 重构流程': '## Refactoring Workflow',
    '- 先用 Claude Code 分析结构': '- Analyze existing structure with Claude Code first',
    '- 提取模式': '- Extract reusable patterns',
    '- 逐步迁移': '- Migrate incrementally, never in one massive change',
    '# Windsurf 开发规则': '# Windsurf Development Standards',
    '# GitHub Copilot 开发规则': '# GitHub Copilot Development Standards',
    '## Copilot 配置': '## Copilot Configuration',
    '## Copilot Prompt': '## Copilot Prompts',
    '# 测试开发规则': '# Testing Standards',
    '# API 开发规则': '# REST API Standards',
    '## RESTful 设计': '## RESTful Design',
    '## 版本控制': '## API Versioning',
    '## 错误格式': '## Error Format',
    '## 认证授权': '## Authentication & Authorization',
    '# 安全开发规则': '# Security Standards',
    '# 数据库开发规则': '# Database Standards',
    '# Docker 开发规则': '# Docker Standards',
    '# Kubernetes 部署规则': '# Kubernetes Deployment Standards',
    '# 前端开发规则': '# Frontend Development Standards',
    '# 后端开发规则': '# Backend Development Standards',
    '# 全栈开发规则': '# Full-Stack Development Standards',
    '# 移动端开发规则': '# Mobile Development Standards',
    '# Web3 智能合约规则': '# Web3 Smart Contract Standards',
    '# AI/ML 开发规则': '# AI/ML Development Standards',
    '# DevOps 规则': '# DevOps Standards',
    '# Monorepo 管理规则': '# Monorepo Management Standards',
    '# Serverless 开发规则': '# Serverless Development Standards',
    '# 微服务开发规则': '# Microservices Standards',
    '# 数据科学开发规则': '# Data Science Standards',
    '# 游戏开发规则': '# Game Development Standards',
    '# 嵌入式开发规则': '# Embedded Systems Standards',
    '# Cursor CSS 开发规则': '# CSS Standards for AI-Assisted Development',
    '# Cursor Docker 开发规则': '# Docker Standards for AI-Assisted Development',
    '# Cursor Kubernetes 部署规则': '# Kubernetes Standards for AI-Assisted Development',
    '# Cursor Terraform 基础设施规则': '# Terraform Infrastructure Standards',
    '# Cursor GraphQL 开发规则': '# GraphQL Standards for AI-Assisted Development',
    '# Cursor Test 开发规则': '# Testing Standards for AI-Assisted Development',
    '# Cursor Git 开发规则': '# Git Workflow Standards for AI-Assisted Development',
    '# Cursor 样式开发规则': '# Styling Standards for AI-Assisted Development',
    '# Cursor 安全规则': '# Security Standards for AI-Assisted Development',
    '# Cursor 数据库规则': '# Database Standards for AI-Assisted Development',
    '# Cursor DevOps 规则': '# DevOps Standards for AI-Assisted Development',
    '# Cursor Monorepo 规则': '# Monorepo Standards for AI-Assisted Development',
    '# Cursor 移动端规则': '# Mobile Standards for AI-Assisted Development',
    '# Cursor 游戏规则': '# Game Development Standards for AI-Assisted Development',
    '# Cursor AI/ML 规则': '# AI/ML Standards for AI-Assisted Development',
    '# Cursor 嵌入式和 IoT 规则': '# Embedded & IoT Standards for AI-Assisted Development',
    '# Cursor Web3 开发规则': '# Web3 Standards for AI-Assisted Development',
    '# Cursor 微服务规则': '# Microservices Standards for AI-Assisted Development',
    '# Cursor Serverless 规则': '# Serverless Standards for AI-Assisted Development',
}

cnt = 0
for cn, en in reps.items():
    try:
        c = content.count(cn)
        if c > 0:
            content = content.replace(cn, en)
            cnt += c
    except Exception:
        pass

open('src/data/rules.ts', 'w', encoding='utf-8').write(content)
cnL = len([l for l in content.split('\n') if re.search(r'[\u4e00-\u9fff]+', l)])
print(f'{cnt} replacements done, {cnL} CN lines remain')
